backlog = 128

# ip should be before port, otherwise the server will not start
ip = 127.0.0.1
port = 8080

ip = 127.0.0.2
port = 8081

error_page_filepath = /home/tdeliot/Desktop/webserver/webserv/srcs/start_server/internal/init_server/a_init_server_rules/5_external_tool/default_error.html
max_size_request_body = 104857600

redirection = /old-page  /new-page

redirection_tmp = /old_tmp  /new_tmp

file_system_root = /website_name  /home/tdeliot/Desktop/webserver/www

#false by default
enable_directory_listing = true

#index.html by default
default_filepath = index.html


enable_upload = true
upload_folder = /home/tdeliot/Desktop/webserver/www/upload

CGI_pathfile = /home/tdeliot/Desktop/webserver/www/CGI/test.py
CGI_pathfile = /home/tdeliot/Desktop/webserver/www/CGI/first_touch.sh


restrained_filepath = only_post_directory/ {POST} only_get_directory/ {GET} delete_forbiden_directory/ {GET,POST}

#default is 10 seconds
client_timeout = 10

#default 30 minutes
session_timeout = 1

#default is 1000 sessions
max_sessions = 200
